// LOCAL HOST
###
GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/65aebdcfbe7ae5d29e53586a
###
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

  {
      "firstname": "Varsha",
      "lastname": "Vaid",
      "cellphone": "987456321",
      "email": "Varsha@bui.edu",
      "countrynationality": "United Kingdom",
      "occupation": "Teacher"
  }
###
PUT http://localhost:3000/contacts/65bc68464bcdf8ddaf2aeea5 HTTP/1.1
content-type: application/json

 {

 "firstname": "Sabrina", 
 "lastname": "Vaid"

 }


###########################################
DELETE http://localhost:3000/contacts/65bc68464bcdf8ddaf2aeea5 HTTP/1.1
